### ISSUE TITLE
API documentation site seems to be broken

### ISSUE THREAD

**Issue by samjetski** [Microsoft/ApplicationInsights-Home#260]
Hi,

On the REST API site, Quickstart and Documentation sections appear to be broken:

https://dev.applicationinsights.io/documentation/overview

I'm getting this error:
```
TypeError: /air/bin/views/partials/markdown.ejs:21
    19|             <div class="row">
    20|                 <div class="col-md-9">
 >> 21|                     <%- md(markdown_content) %>
    22|                 </div>
    23|             </div>
    24|         </div>

token.attrGet is not a function
    at tokens.filter.filter.forEach.token (/air/node_modules/markdown-it-anchor/index.js:64:26)
    at Array.forEach (<anonymous>)
    at Array.md.core.ruler.push.state (/air/node_modules/markdown-it-anchor/index.js:58:8)
    at Core.process (/air/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/air/node_modules/markdown-it/lib/index.js:519:13)
    at MarkdownIt.render (/air/node_modules/markdown-it/lib/index.js:539:36)
    at markdown (/air/bin/markdownWrapper.js:31:15)
    at Object.app.locals.md (/air/bin/server.js:27:16)
    at eval (eval at compile (/air/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:11:17)
    at returnedFn (/air/node_modules/ejs/lib/ejs.js:653:17)
```

**Comment by Dmitry-Matveev** [comment]
@samjetski, was it fixed? I can see that page opens successfully now (with some issues in console that are different from this particular one).

**Comment by SergeyKanzhelev** [comment]
Please re-open if it still broken for you
