### ISSUE TITLE
formatting exception when enabling App Insight for Azure function. 

### ISSUE THREAD

**Issue by tyagiparth** [microsoft/ApplicationInsights-Home#329]
I have deployed an Azure v2 function and enabled App Insight on top of it. I'm getting a `Formatter exception. `
`Format string can be only "D", "d", "N", "n", "P", "p", "B", "b", "X" or "x".` at  System.Private.CoreLib
```
at System.Guid.TryFormat(Span`1 destination, Int32& charsWritten, ReadOnlySpan`1 format)
   at System.Guid.System.ISpanFormattable.TryFormat(Span`1 destination, Int32& charsWritten, ReadOnlySpan`1 format, IFormatProvider provider)
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.Extensions.Logging.Internal.LogValuesFormatter.Format(Object[] values)
   at Microsoft.Extensions.Logging.Internal.FormattedLogValues.ToString()
   at Microsoft.Extensions.Logging.LoggerExtensions.MessageFormatter(Object state, Exception error)
   at Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\ApplicationInsightsLogger.cs:line 56
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
```

This exception only occurs when the app insight is enabled for the function. We also have a custom implementation for creating the telemetry data with the help of App Insight Nugets which is off loaded to Log analytics work space. 
This exception doesn't' occur with the custom implementation.  

Azure SDK Version is: `Microsoft.NET.Sdk.Functions-1.0.26`

**Comment by lmolkova** [comment]
@vatsparth 
thanks for reporting this! 
Do you know if it happens when function log something or when you call logger from your code? 
If it is something you log, can you share which arguments you pass to Log* method and which scopes do you put?
You mentioned that in custom implementation this exception does not happen, do you try to format message there? 

`string formattedMessage = formatter?.Invoke(state, exception);`

It seems that something expects guid, but it is not guid.  Does your function modify/customize any Functions logger scopes?

/cc @brettsam

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
