### ISSUE TITLE
SnapshotUploader Error scanning for PDBs

### ISSUE THREAD

**Issue by StandBackBurrito** [Microsoft/ApplicationInsights-Home#335]
We are seeing traces in our log where the SnapShotUploader is getting an access denied while looking for local PDB in our DFSR folder.

Is there a way to keep `SearchForLocalPdbs` from looking in certain folders?
```
SnapshotUploader (Internal): Error scanning for PDBs: System.UnauthorizedAccessException: Access to the path '\wwwroot\somefolder\App_Data\somefolder\DfsrPrivate' is denied.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at Microsoft.ApplicationInsights.SnapshotCollector.Uploader.Uploader.SearchForLocalPdbs(CancellationToken cancellationToken)
```

**Comment by SergeyKanzhelev** [comment]
@pharring can you help?

**Comment by pharring** [comment]
@StandBackBurrito thanks for the question. The error is benign. If we see any Exception when scanning for PDBs, we remove the folder from the search list. So you should see this just once (per run of the SnapshotUploader) and it is just a diagnostic; it's non-fatal.
