### ISSUE TITLE
Status Monitor fails to start on Windows Server 2019

### ISSUE THREAD

**Issue by sadjadbp** [microsoft/ApplicationInsights-Home#343]
Updated my servers to Windows Server 2019, and now Application Status Monitor cannot start with the error below.

Tried starting as admin or uninstall and reinstall, stopped Windows Defender, but nothing helped.

```
An unhandled exception occurred: System.Runtime.InteropServices.COMException (0x800705AA): Insufficient 
system resources exist to complete the requested service. (Exception from HRESULT: 0x800705AA)
   at System.Runtime.CompilerServices.AsyncServices.<ThrowAsync>b__0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 
numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, 
Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback 
callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, 
Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, 
Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, 
ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, 
Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 
numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, 
Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, 
Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Microsoft.Diagnostics.Agent.StatusMonitor.App.Main()
```

**Comment by sadjadbp** [comment]
![image](https://user-images.githubusercontent.com/6307366/56474654-8770c300-6431-11e9-9c0d-3b5b9a04de23.png)

**Comment by SergeyKanzhelev** [comment]
My **guess** will be that you need to install IIS management component. Use windows add/remove features dialog

![image](https://user-images.githubusercontent.com/9950081/56771103-99709f80-676a-11e9-98b1-56de6d17b15e.png)

**Comment by sadjadbp** [comment]
It's a Windows Server 2019 and I think I already have that

![image](https://user-images.githubusercontent.com/6307366/56771315-1f8ce600-676b-11e9-8231-dd1cdce5787b.png)

**Comment by MS-TimothyMothra** [comment]
How much memory do you have on this server?
This doesn't sound like a StatusMonitor problem. If you notice in that call stack, the main method is failing with the exception:

> Insufficient system resources exist to complete the requested service

**Comment by sadjadbp** [comment]
No memory issue, have 8GB free

![image](https://user-images.githubusercontent.com/6307366/56771851-c0c86c00-676c-11e9-82cd-2d80796b734d.png)

Have the same issue on 6 servers all Windows Server 2019.

**Comment by MS-TimothyMothra** [comment]
I spoke to @sadjadbp offline and asked him to try StatusMonitor's replacement, IISConfigurator.

**Comment by MS-TimothyMothra** [comment]
Today I've released the Release Candidate for Status Monitor v2.
Because this is the replacement for the original Status Monitor, I'm going to close this issue.

Please review or documentation to get started: https://docs.microsoft.com/en-us/azure/azure-monitor/app/status-monitor-v2-overview
