### ISSUE TITLE
Type System.Runtime.Remoting.ObjRef and the types derived from it (such as System.Runtime.Remoting.ObjRef) are not permitted to be deserialized at this security level.

### ISSUE THREAD

**Issue by mangeshparanjape** [microsoft/ApplicationInsights-Home#392]
Hi
We are experiencing an issue when we enabled Azure Application Insights monitoring for ASP.NET MVC App hosted in IIS on Windows server. This Web App uses .NET Remoting to the App server.

Below is the error:
Type System.Runtime.Remoting.ObjRef and the types derived from it (such as System.Runtime.Remoting.ObjRef) are not permitted to be deserialized at this security level.
ERROR_DESC	Server stack trace: at System.Runtime.Serialization.FormatterServices.CheckTypeSecurity(Type t, TypeFilterLevel securityLevel) at System.Runtime.Serialization.Formatters.Binary.ObjectReader.CheckSecurity(ParseRecord pr) at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject(ParseRecord pr) at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run() at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage) at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage) at System.Runtime.Remoting.Channels.CoreChannel.DeserializeBinaryRequestMessage(String objectUri, Stream inputStream, Boolean bStrictBinding, TypeFilterLevel securityLevel) at System.Runtime.Remoting.Channels.BinaryServerFormatterSink.ProcessMessage(IServerChannelSinkStack sinkStack, IMessage requestMsg, ITransportHeaders requestHeaders, Stream requestStream, IMessage& responseMsg, ITransportHeaders& responseHeaders, Stream& responseStream) Exception rethrown at [0]: at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg) at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)

**Comment by Dmitry-Matveev** [comment]
@mangeshparanjape, are you running this application in Full Trust mode? I think only Full Trust mode is currently supported by Application Insights SDK, so if it would invoke a serialization of the secure object for telemetry purposes, the security exception may get thrown.

**Comment by dvnu** [comment]
@Dmitry-Matveev I'm having the same error in the same scenario. A web application that uses remoting to make server calls after installing Application Insights Agent.

Server stack trace:
   at System.Runtime.Serialization.FormatterServices.CheckTypeSecurity(Type t, TypeFilterLevel securityLevel)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.CheckSecurity(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Remoting.Channels.CoreChannel.DeserializeBinaryRequestMessage(String objectUri, Stream inputStream, Boolean bStrictBinding, TypeFilterLevel securityLevel)
   at System.Runtime.Remoting.Channels.BinaryServerFormatterSink.ProcessMessage(IServerChannelSinkStack sinkStack, IMessage requestMsg, ITransportHeaders requestHeaders, Stream requestStream, IMessage& responseMsg, ITransportHeaders& responseHeaders, Stream& responseStream) 


Application is configured to run in full trust 

<system.web>
    <trust level="Full" originUrl="" />


I can replicate this on our QA environment and I'm more than happy to help pin point the issue and even fix it, but I'll need some guidance.

**Comment by Dmitry-Matveev** [comment]
@SergeyKanzhelev , can it be related to IL code changes AI agent can be doing? (I assume @dvnu means AI Status Monitor and code-less onboarding when light profiler is getting configured for IIS)

I can't think of the other reason for security check failures after agent installation off top of my head.

**Comment by dvnu** [comment]
@Dmitry-Matveev @SergeyKanzhelev yes

For you reference this was the approach followed: https://docs.microsoft.com/en-us/azure/azure-monitor/app/azure-vm-vmss-apps
And yes it's a codeless deployment

**Comment by dvnu** [comment]
Hey @Dmitry-Matveev @SergeyKanzhelev 
Any pointers to help pinpoint the problem ? 
I'm more than happy to troubleshoot and narrow the issue on my own and help solve if needed but I would really appreciate your input on this
