### ISSUE TITLE
Microsoft.ApplicationInsights.SnapshotCollector 1.3.6 breaks on Docker

### ISSUE THREAD

**Issue by cdemi** [microsoft/ApplicationInsights-Home#452]
After upgrading my project to Microsoft.ApplicationInsights.SnapshotCollector 1.3.6 I am getting an Application Crash on Startup.

```
newslettercurator      | fail: Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider[48]
newslettercurator      |       An error occurred while reading the key ring.
newslettercurator      | System.AggregateException: An error occurred while writing to logger(s). (Could not find a suitable shadow copy folder.)
newslettercurator      |  ---> Microsoft.ApplicationInsights.SnapshotCollector.UploaderStartException: Could not find a suitable shadow copy folder.
newslettercurator      |    at Microsoft.ApplicationInsights.SnapshotCollector.SnapshotCollectorTelemetryProcessor.SetAndVerifyWorkingFolders(ConnectionString connectionString)
newslettercurator      |    at Microsoft.ApplicationInsights.SnapshotCollector.SnapshotCollectorTelemetryProcessor.IsProcessorEnabled(ITelemetry item)
newslettercurator      |    at Microsoft.ApplicationInsights.SnapshotCollector.SnapshotCollectorTelemetryProcessor.Process(ITelemetry item)
newslettercurator      |    at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Process(ITelemetry item)
newslettercurator      |    at Microsoft.ApplicationInsights.Extensibility.TelemetrySink.Process(ITelemetry item)
newslettercurator      |    at Microsoft.ApplicationInsights.Shared.Extensibility.Implementation.PassThroughProcessor.Process(ITelemetry item)
newslettercurator      |    at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Process(ITelemetry item)
newslettercurator      |    at Microsoft.ApplicationInsights.TelemetryClient.Track(ITelemetry telemetry)
newslettercurator      |    at Microsoft.ApplicationInsights.TelemetryClient.TrackTrace(TraceTelemetry telemetry)
newslettercurator      |    at Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
newslettercurator      |    at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
newslettercurator      |    --- End of inner exception stack trace ---
newslettercurator      |    at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
newslettercurator      |    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
newslettercurator      |    at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
newslettercurator      |    at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass5_0`1.<Define>g__Log|0(ILogger logger, T1 arg1, Exception exception)
newslettercurator      |    at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass5_0`1.<Define>b__1(ILogger logger, T1 arg1, Exception exception)
newslettercurator      |    at Microsoft.Extensions.Logging.LoggingExtensions.NoXMLEncryptorConfiguredKeyMayBePersistedToStorageInUnencryptedForm(ILogger logger, Guid keyId)
newslettercurator      |    at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)
newslettercurator      |    at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate)
newslettercurator      |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
newslettercurator      |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
newslettercurator      |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)
```

Using `mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim`

**Comment by Dmitry-Matveev** [comment]
@pharring should be able to help here.

**Comment by pharring** [comment]
@cdemi Did this ever work? buster-slim is a Linux image and SnapshotCollector is for Windows only (at this point)

**Comment by pharring** [comment]
@cdemi I recommend uninstalling Microsoft.ApplicationInsights.SnapshotCollector 1.3.6 from your Linux apps. If, for some reason, you still need the Snapshot Collector nuget (because your app also runs on Windows), then by all means downgrade to 1.3.5.

If you have different configs/appsettings.json for Linux and Windows, I might be able to offer a workaround that will allow you to keep 1.3.6 on both (basically setting IsEnabled to false in the configuration for Linux).

Otherwise, I'll add it to the backlog for 1.3.7

**Comment by cdemi** [comment]
It actually worked in 1.3.5. I was unaware that this is Windows only. Fortunately I am building only for Linux so I will remove this dependency
