### ISSUE TITLE
Microsoft.ApplicationInsights.SnapshotCollector.UploaderStartException: Could not find a suitable shadow copy folder.

### ISSUE THREAD

**Issue by jpmaistrebazin** [microsoft/ApplicationInsights-Home#466]
After ugrading  my project to Microsoft.ApplicationInsights.SnapshotCollector 1.3.6 I am getting an Application Crash on Startup when hosting with IIS.

```
Application: w3wp.exe
CoreCLR Version: 4.700.20.6602
.NET Core Version: 3.1.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AggregateException: An error occurred while writing to logger(s). (Could not find a suitable shadow copy folder.)
 ---> Microsoft.ApplicationInsights.SnapshotCollector.UploaderStartException: Could not find a suitable shadow copy folder.
   at Microsoft.ApplicationInsights.SnapshotCollector.SnapshotCollectorTelemetryProcessor.SetAndVerifyWorkingFolders(ConnectionString connectionString)
   at Microsoft.ApplicationInsights.SnapshotCollector.SnapshotCollectorTelemetryProcessor.IsProcessorEnabled(ITelemetry item)
   at Microsoft.ApplicationInsights.SnapshotCollector.SnapshotCollectorTelemetryProcessor.Process(ITelemetry item)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Process(ITelemetry item)
   at Microsoft.ApplicationInsights.Extensibility.TelemetrySink.Process(ITelemetry item)
   at Microsoft.ApplicationInsights.Shared.Extensibility.Implementation.PassThroughProcessor.Process(ITelemetry item)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Process(ITelemetry item)
   at Microsoft.ApplicationInsights.TelemetryClient.Track(ITelemetry telemetry)
   at Microsoft.ApplicationInsights.TelemetryClient.TrackTrace(TraceTelemetry telemetry)
   at Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass4_0.<Define>b__0(ILogger logger, Exception exception)
   at Microsoft.Extensions.Logging.LoggingExtensions.UsingInmemoryRepository(ILogger logger)
   at Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository..ctor(ILoggerFactory loggerFactory)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetFallbackKeyRepositoryEncryptorPair()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager..ctor(IOptions`1 keyManagementOptions, IActivator activator, ILoggerFactory loggerFactory, IDefaultKeyStorageDirectories keyStorageDirectories)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager..ctor(IOptions`1 keyManagementOptions, IActivator activator, ILoggerFactory loggerFactory)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Oozym.Web.Api.NotificationHub.Program.Main(String[] args) in C:\_Oozym\Code\tfs\Oozym.Web.Api.NotificationHub\Oozym.Web.Api.NotificationHub\Program.cs:line 18
```

**Comment by TimothyMothra** [comment]
@pharring can you please take a look?

**Comment by pharring** [comment]
Acknowledged.
```
UploaderStartException: Could not find a suitable shadow copy folder.
```

**Comment by pharring** [comment]
Background: The SnapshotCollector assembly embeds all its support files as resources and it extracts those files to disk at runtime. The ShadowCopyFolder is the folder on disk into which those files are extracted. To find a suitable ShadowCopyFolder the Snapshot Collector searches through a few different environment variables in order:
- Fabric_Folder_App_Temp
- LOCALAPPDATA
- APPDATA
- TEMP

For each one, if the environment variable exists, Snapshot Collector checks to see if the folder exists and is writable. As soon as a writable location is found, that becomes the ShadowCopyFolder. If none is writable, then you get the "Could not find a suitable shadow copy folder" exception message.

Now, we did change things around in 1.3.6 so that the SetAndVerifyWorkingFolders call is made earlier in startup. So, this may have been a problem in prior versions that went undetected -- although, if it did, Snapshot Collector would not have worked at all. However, while it is telling you something important, the exception should not have been allowed to escape the `Microsoft.ApplicationInsights.SnapshotCollector.SnapshotCollectorTelemetryProcessor.Process` method. That's a bug and I've entered it for our 1.3.7 backlog.

In the meantime, to address your issue, you could manually specify a ShadowCopyFolder in the SnapshotCollectorConfiguration. Obviously, you need to find a folder location that your app has permissions to write into. It needs about 50MB of space. Assuming you're using the standard DI mechanism for enabling SnapshotCollector, you would set it in your appsettings.json file:
```json
{
  "SnapshotCollector" : {
    "ShadowCopyFolder" : "C:\\Your\\Folder"
  }
}
```

The value can also include an environment variable. e.g.
```
"ShadowCopyFolder" : "%TEMP%\\ShadowCopy"
```
assuming you can find a suitable folder.

Now, the question becomes "What is unusual about your environment?" because that shadow copy folder algorithm works for all other IIS environments we've come across. And, frankly, if even %TEMP% (which is really the "last resort" location) is not writable the rest of Snapshot Collector isn't going to work because we create the dumps and log files in a folder under %TEMP%. Please tell me more about your IIS hosting environment. For example:
Is your environment particularly locked down?
Is your IIS host running under very restricted credentials?
What OS are you using?
I'd love to learn more to see if there's something we can do in Snapshot Collector to handle your case automatically.

**Comment by jpmaistrebazin** [comment]
_Is your environment particularly locked down?_
No

_Is your IIS host running under very restricted credentials?_
Not really, but just application pool and IIS_IUSRS had permissions to read/write in application directory

_What OS are you using?_
Windows Server 2019 Datacenter

I try specify manually ShadowCopyFolder to know isssue. Maybe a permission problem. I check that
Thks

**Comment by jpmaistrebazin** [comment]
Ok, I found ! I had changed application pool and I forgot to put permission folder. I revised it, and its works ! Thanks to help
