### ISSUE TITLE
Running node 12 app with ApplicationInsights

### ISSUE THREAD

**Issue by NatMarchand** [microsoft/ApplicationInsights-Home#470]
When runnning a nodejs app on linux app service deployed as a zip (WEBSITE_RUN_FROM_PACKAGE=1), as soon I activate Application Insights, I encounter an error which prevents my app from starting :
```
2020-03-26T12:19:06.462311480Z   _____                               
2020-03-26T12:19:06.462346280Z   /  _  \ __________ _________   ____  
2020-03-26T12:19:06.462352880Z  /  /_\  \___   /  |  \_  __ \_/ __ \ 
2020-03-26T12:19:06.462357280Z /    |    \/    /|  |  /|  | \/\  ___/ 
2020-03-26T12:19:06.462361680Z \____|__  /_____ \____/ |__|    \___  >
2020-03-26T12:19:06.462365980Z         \/      \/                  \/ 
2020-03-26T12:19:06.462370179Z A P P   S E R V I C E   O N   L I N U X
2020-03-26T12:19:06.462374379Z 
2020-03-26T12:19:06.462378279Z Documentation: http://aka.ms/webapp-linux
2020-03-26T12:19:06.462382179Z NodeJS quickstart: https://aka.ms/node-qs
2020-03-26T12:19:06.462402779Z NodeJS Version : v12.13.0
2020-03-26T12:19:06.462406479Z Note: Any data outside '/home' is not persisted
2020-03-26T12:19:06.462410279Z 
2020-03-26T12:19:06.505540277Z Oryx Version: 0.2.20191105.2, Commit: 67e159d71419415435cb5d10c05a0f0758ee8809, ReleaseTagName: 20191105.2
2020-03-26T12:19:06.507156666Z Cound not find build manifest file at '/home/site/wwwroot/oryx-manifest.toml'
2020-03-26T12:19:06.507261965Z Could not find operation ID in manifest. Generating an operation id...
2020-03-26T12:19:06.507418764Z Build Operation ID: dcecc6f6-a910-4464-a0a9-dcfd9c9610a4
2020-03-26T12:19:07.091266280Z Environment Variables for Application Insight's Codeless Configuration exists..
2020-03-26T12:19:07.091955875Z Writing output script to '/home/site/wwwroot/oryx-appinsightsloader.js'
2020-03-26T12:19:07.494076062Z Writing output script to '/opt/startup/startup.sh'
2020-03-26T12:19:07.965631864Z Running #!/bin/sh
2020-03-26T12:19:07.966622457Z 
2020-03-26T12:19:07.966645057Z # Enter the source directory to make sure the script runs where the user expects
2020-03-26T12:19:07.966650857Z cd "/home/site/wwwroot"
2020-03-26T12:19:07.966655157Z 
2020-03-26T12:19:07.967646850Z export NODE_PATH=$(npm root --quiet -g):$NODE_PATH
2020-03-26T12:19:07.967659650Z if [ -z "$PORT" ]; then
2020-03-26T12:19:07.967664650Z 		export PORT=8080
2020-03-26T12:19:07.967669149Z fi
2020-03-26T12:19:07.968491744Z 
2020-03-26T12:19:07.968504144Z export NODE_OPTIONS='--require ./oryx-appinsightsloader.js ' $NODE_OPTIONS
2020-03-26T12:19:07.968509444Z PATH="$PATH:/home/site/wwwroot" npm start -- -p 8080
2020-03-26T12:19:08.382781646Z internal/modules/cjs/loader.js:797
2020-03-26T12:19:08.382813345Z     throw err;
2020-03-26T12:19:08.382819345Z     ^
2020-03-26T12:19:08.382823645Z 
2020-03-26T12:19:08.382827745Z Error: Cannot find module './oryx-appinsightsloader.js'
2020-03-26T12:19:08.382832045Z Require stack:
2020-03-26T12:19:08.382843545Z - internal/preload
2020-03-26T12:19:08.382848145Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
2020-03-26T12:19:08.382852245Z     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
2020-03-26T12:19:08.382856345Z     at Module.require (internal/modules/cjs/loader.js:849:19)
2020-03-26T12:19:08.382860445Z     at Module._preloadModules (internal/modules/cjs/loader.js:1125:12)
2020-03-26T12:19:08.382864545Z     at loadPreloadModules (internal/bootstrap/pre_execution.js:443:5)
2020-03-26T12:19:08.382868645Z     at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:62:3)
2020-03-26T12:19:08.382872745Z     at internal/main/run_main_module.js:7:1 {
2020-03-26T12:19:08.382876845Z   code: 'MODULE_NOT_FOUND',
2020-03-26T12:19:08.382880945Z   requireStack: [ 'internal/preload' ]
2020-03-26T12:19:08.382885145Z }
```

I guess that it's because the filesystem is readonly. Is there anything I can do to fix the error ?

**Comment by TimothyMothra** [comment]
@markwolff please take a look

**Comment by markwolff** [comment]
Seems to be using an older version of Oryx. /cc @microsoft/oryx-contrib
